---
parameters:
  NAMESPACE:
    description: "The Kubernetes namespace into which you want to deploy (e.g. `prod`)."
secrets:
  KUBERNETES_URL:
    description: "The URL of the Kubernetes cluster API server. This needs to be reachable from the GitHub Actions runner."
  KUBERNETES_SECRET:
    description: "The secret associated with the service account that has access to the Kubernetes cluster."
---
name: Deploy to Kubernetes
on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_URL: ghcr.io/${{ github.repository }}:${{ github.sha }}

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uncomment this action if you are targeting platforms other than amd64
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_URL }}
          labels: |
            dockerfile-path=https://github.com/${{ github.repository }}/blob/${{ github.sha }}/Dockerfile

      - name: Build image and push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          # Adjust the platform if required
          # platforms: linux/arm64
          push: true
          tags: ${{ env.IMAGE_URL }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          pull-images: false
          namespace: getactions.NAMESPACE
          manifests: |
            kubernetes
          images: |
            ${{ env.IMAGE_URL }}
