---
parameters:
  IAC_PATH:
    description: "The path where all your Terraform files live (should be relative to the root of your repository)"
---
name: Terraform CI
on:
  pull_request:
    paths:
      - "getactions.IAC_PATH"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache tflint plugin directory
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3

      - name: terraform init
        run: terraform init

      - name: init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -check -list=false || echo "Terraform files are not formatted properly. Please run 'terraform fmt' to fix the formatting."

      - name: tflint
        run: tflint --format compact --recursive
