---
secrets:
  VERCEL_TEAM_ID:
    description: "The ID of your team on Vercel. You can find it in the settings of your team under 'General' > 'Team ID'."
  VERCEL_PROJECT_ID:
    description: "The ID of your project on Vercel. You can find it in the settings of your project under 'General' > 'Project ID'."
  VERCEL_TOKEN:
    description: "The token for interacting with the Vercel API. You can learn more on how to create the token here: https://vercel.com/guides/how-do-i-use-a-vercel-api-access-token"
---
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-as-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Environment Information from Vercel
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
