---
parameters:
  APP_NAME:
    description: "The name of your application"
  GCP_REGION:
    description: "The region where you want to deploy your application"
secrets:
  GCP_PROJECT_ID:
    description: "The project ID of your Google Cloud Platform project. You can find it in the project switcher."
  GCP_CREDENTIALS:
    description: "The service account credentials for authenticating with Google Cloud Platform. This is the keyfile JSON you downloaded when creating the service account."
---
name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy getactions.APP_NAME \
        --region getactions.GCP_REGION \
        --source . \
        --allow-unauthenticated
